server:
  port: 9090

spring: 
  application:
    name: ms-product
  datasource:
    platform: MYSQL
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb;sql.syntax_ora=true
    username: sa
    password: 
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql

mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.freud.test